### ISSUE TITLE
Padding

### ISSUE THREAD

**Issue by Nyathene** [Haroub-S/your-tribe-profile-card#4]
De padding bij Section 2 en Section 3 is niet hetzelfde: Bij section 2 staat er in de CSS expliciet "padding: 1em;", maar bij section 3 staat er geen padding, en geld de padding van 10 pixels van de (misschien overbodige) CSS voor "section"

En dit is misschien meer een stijlverschil dan een issue, maar het lijkt erop dat de inhoud van de kaart een beetje naar links staat. Dit zou mogelijk verbeterd kunnen worden met

**Comment by Haroub-S** [comment]
bedankt
